/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test_roman.ts" instead.
 */

#include <check.h>

#line 1 "test_roman.ts"
#include <stdio.h>
#include "roman.h"

START_TEST(converts_zero_to_empty_string)
{
#line 5
        ck_assert_str_eq("", rom_ToRoman(0));

}
END_TEST

START_TEST(converts_one_to_I)
{
#line 8
        ck_assert_str_eq("I", rom_ToRoman(1));

}
END_TEST

START_TEST(converts_string_of_numerals_to_arabic)
{
#line 11
        ck_assert_str_eq("III", rom_ToRoman(3));

}
END_TEST

START_TEST(converts_multiple_digit_numerals_to_arabic)
{
#line 14
        ck_assert_str_eq("IV", rom_ToRoman(4));

}
END_TEST

START_TEST(converts_five_to_V)
{
#line 17
        ck_assert_str_eq("V", rom_ToRoman(5));

}
END_TEST

START_TEST(converts_forty_four_to_XCIV)
{
#line 20
        ck_assert_str_eq("XLIV", rom_ToRoman(44));

}
END_TEST

START_TEST(converts_empty_to_zero)
{
#line 23
        ck_assert_int_eq(0, rom_ToArabic(""));

}
END_TEST

START_TEST(converts_I_to_one)
{
#line 26
        ck_assert_int_eq(1, rom_ToArabic("I"));

}
END_TEST

START_TEST(converts_two_of_same_numeral_in_a_row)
{
#line 29
        ck_assert_int_eq(2, rom_ToArabic("II"));

}
END_TEST

START_TEST(converts_single_term_roman_to_arabic)
{
#line 32
        ck_assert_int_eq(100, rom_ToArabic("C"));

}
END_TEST

START_TEST(converts_two_digit_single_term_roman_to_arabic)
{
#line 35
        ck_assert_int_eq(9, rom_ToArabic("IX"));

}
END_TEST

START_TEST(converts_multiple_two_digit_terms_roman_to_arabic)
{
#line 38
        ck_assert_int_eq(29, rom_ToArabic("XXIX"));
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, converts_zero_to_empty_string);
    tcase_add_test(tc1_1, converts_one_to_I);
    tcase_add_test(tc1_1, converts_string_of_numerals_to_arabic);
    tcase_add_test(tc1_1, converts_multiple_digit_numerals_to_arabic);
    tcase_add_test(tc1_1, converts_five_to_V);
    tcase_add_test(tc1_1, converts_forty_four_to_XCIV);
    tcase_add_test(tc1_1, converts_empty_to_zero);
    tcase_add_test(tc1_1, converts_I_to_one);
    tcase_add_test(tc1_1, converts_two_of_same_numeral_in_a_row);
    tcase_add_test(tc1_1, converts_single_term_roman_to_arabic);
    tcase_add_test(tc1_1, converts_two_digit_single_term_roman_to_arabic);
    tcase_add_test(tc1_1, converts_multiple_two_digit_terms_roman_to_arabic);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
