/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test_roman.ts" instead.
 */

#include <check.h>

#line 1 "test_roman.ts"
#include <stdio.h>
#include "libroman.h"

START_TEST(converts_one_to_I)
{
#line 5
        ck_assert_str_eq("I", rom_ToRoman(1));

}
END_TEST

START_TEST(converts_three_to_III)
{
#line 8
        ck_assert_str_eq("III", rom_ToRoman(3));

}
END_TEST

START_TEST(converts_four_to_IV)
{
#line 11
        ck_assert_str_eq("IV", rom_ToRoman(4));

}
END_TEST

START_TEST(converts_five_to_V)
{
#line 14
        ck_assert_str_eq("V", rom_ToRoman(5));

}
END_TEST

START_TEST(converts_forty_four_to_XCIV)
{
#line 17
        ck_assert_str_eq("XLIV", rom_ToRoman(44));

}
END_TEST

START_TEST(converts_empty_to_zero)
{
#line 20
        ck_assert_int_eq(0, rom_ToArabic(""));
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, converts_one_to_I);
    tcase_add_test(tc1_1, converts_three_to_III);
    tcase_add_test(tc1_1, converts_four_to_IV);
    tcase_add_test(tc1_1, converts_five_to_V);
    tcase_add_test(tc1_1, converts_forty_four_to_XCIV);
    tcase_add_test(tc1_1, converts_empty_to_zero);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
