/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test_roman_arithmetic.ts" instead.
 */

#include <check.h>

#line 1 "test_roman_arithmetic.ts"
#include <stdio.h>
#include "roman.h"

START_TEST(add_one_to_one_to_get_two)
{
#line 5
        ck_assert_str_eq(addRoman("I", "I"), "II");

}
END_TEST

START_TEST(add_multiple_single_numerals_to_get_a_subtractive)
{
#line 8
        ck_assert_str_eq(addRoman("II", "II"), "IV");

}
END_TEST

START_TEST(add_multiple_large_numerals)
{
#line 11
        ck_assert_str_eq(addRoman("CXXIV", "MIX"), "MCXXXIII");
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, add_one_to_one_to_get_two);
    tcase_add_test(tc1_1, add_multiple_single_numerals_to_get_a_subtractive);
    tcase_add_test(tc1_1, add_multiple_large_numerals);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
